services:
  backend:
    build:
      context: .
      dockerfile: deploy/backend/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static_volume:/app/static_root
      - media_volume:/app/src/core/media
    env_file:
      - local.env
    depends_on:
      - db
      - redis

  channels:
    build:
      context: .
      dockerfile: deploy/backend/Dockerfile
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    volumes:
      - static_volume:/app/static_root
      - media_volume:/app/src/core/media
    env_file:
      - local.env
    depends_on:
      - db
      - redis

  db:
    build:
      context: .
      dockerfile: deploy/db/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - local.env

  redis:
    image: redis:7

  nginx:
    image: nginx:1.25
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static_root
      - media_volume:/app/src/core/media
    depends_on:
      - backend
      - channels

volumes:
  postgres_data:
  static_volume:
  media_volume: