# Generated by Django 5.2.7 on 2026-02-02 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='seo_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock'),
        ),
        migrations.AddField(
            model_name='newsandactions',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, to='cms.gallery'),
        ),
        migrations.AddField(
            model_name='newsandactions',
            name='seo_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock'),
        ),
        migrations.AddField(
            model_name='page',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, to='cms.gallery'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.cinema'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.hall'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.movie'),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schedule'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.schedule'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('schedule', 'row', 'seat')},
        ),
    ]
