# Generated by Django 5.2.7 on 2026-02-02 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='banners/')),
                ('text', models.TextField(blank=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='contacts/')),
                ('cinema_name', models.CharField(max_length=120)),
                ('cinema_name_uk', models.CharField(max_length=120, null=True)),
                ('cinema_name_en', models.CharField(max_length=120, null=True)),
                ('address', models.CharField(max_length=120)),
                ('address_uk', models.CharField(max_length=120, null=True)),
                ('address_en', models.CharField(max_length=120, null=True)),
                ('phone_number', models.CharField(max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cinema_gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Новини кінотеатру', max_length=256)),
                ('template_file', models.FileField(upload_to='mailing_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=120)),
                ('title_uk', models.CharField(max_length=120, null=True)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('keywords', models.CharField(max_length=120)),
                ('keywords_uk', models.CharField(max_length=120, null=True)),
                ('keywords_en', models.CharField(max_length=120, null=True)),
                ('description', models.TextField()),
                ('description_uk', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('is_promo', models.BooleanField()),
                ('banner_component', models.ManyToManyField(blank=True, related_name='banners', to='cms.bannercomponent')),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('title_uk', models.CharField(max_length=120, null=True)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('description', models.TextField()),
                ('description_uk', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('main_image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=120)),
                ('address_uk', models.CharField(max_length=120, null=True)),
                ('address_en', models.CharField(max_length=120, null=True)),
                ('gallery_image', models.ManyToManyField(to='cms.gallery')),
                ('seo_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('title_uk', models.CharField(max_length=120, null=True)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('description', models.TextField()),
                ('description_uk', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('main_image', models.ImageField(upload_to='movies_main/')),
                ('trailer_url', models.URLField()),
                ('is_2D', models.BooleanField()),
                ('is_3D', models.BooleanField()),
                ('date_of_show', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_end_show', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('images', models.ManyToManyField(to='cms.gallery')),
                ('seo_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('description_uk', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('scheme_of_hall', models.FileField(blank=True, null=True, upload_to='schemes_hall/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='halls_banners/')),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('is_removable', models.BooleanField(default=True)),
                ('gallery_image', models.ManyToManyField(to='cms.gallery')),
                ('id_cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.cinema')),
                ('seo_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ManyToManyField(to='cms.contactcomponent')),
                ('seo_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='ThroughBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('background', models.CharField()),
                ('banner_component', models.ManyToManyField(to='cms.bannercomponent')),
            ],
        ),
    ]
